# Generated by Django 5.1 on 2024-08-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="qr_code",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
