# Generated by Django 5.1 on 2024-09-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_qr_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.AddField(
            model_name="product",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
