# Generated by Django 5.1 on 2024-09-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_product_is_active_product_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
