# Generated by Django 5.1 on 2024-09-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cartitem_quantity_alter_cart_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
